[workspace]
resolver = "2"

members = [
    "async-executor",
    "reika-macros",
    "reika-storage",
    "reika-reactor",
    "reika",
    "examples/cat",
    "examples/cp",
    "examples/playground",
    "examples/tcpecho"
]
